#!/bin/bash
#
# Cleanup Artifacts Script
#
# Removes temporary and generated files that should not be committed.
#
# Usage:
#   ./scripts/cleanup_artifacts.sh              # Clean temporary artifacts
#   ./scripts/cleanup_artifacts.sh --force      # No prompts
#   ./scripts/cleanup_artifacts.sh --prepare    # Full cleanup for git repo
#
# Modes:
#   Default:    Removes plan files, crash logs, misplaced backups
#   --prepare:  Also removes .terraform/, state files, terraform.tfvars
#               Use before initial git commit or to reset to clean state
#
# Safe files (never removed):
#   - Source code (.tf files)
#   - Example files (terraform.tfvars.example)
#   - Documentation
#

set -e

# ==============================================================================
# Setup
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ==============================================================================
# Functions
# ==============================================================================

print_header() {
    echo ""
    echo "========================================"
    echo "  Terraform Artifact Cleanup"
    echo "========================================"
    echo ""
}

print_found() {
    echo -e "  ${YELLOW}Found:${NC} $1"
}

print_removed() {
    echo -e "  ${GREEN}Removed:${NC} $1"
}

print_clean() {
    echo -e "  ${GREEN}Clean:${NC} $1"
}

print_info() {
    echo -e "  ${BLUE}Info:${NC} $1"
}

# ==============================================================================
# Artifact Detection
# ==============================================================================

detect_artifacts() {
    local prepare_mode=$1
    ARTIFACTS=()
    DIRS_TO_REMOVE=()

    # Plan files in providers/
    for f in "$PROJECT_ROOT"/providers/*.tfplan "$PROJECT_ROOT"/providers/tfplan; do
        if [[ -f "$f" ]]; then
            ARTIFACTS+=("$f")
            print_found "$(basename "$f") (plan file)"
        fi
    done

    # State backups in wrong location (providers/ instead of backup/)
    for f in "$PROJECT_ROOT"/providers/*.backup* "$PROJECT_ROOT"/providers/terraform.tfstate.backup; do
        if [[ -f "$f" ]]; then
            ARTIFACTS+=("$f")
            print_found "$(basename "$f") (misplaced backup)"
        fi
    done

    # Crash logs anywhere in project
    for f in "$PROJECT_ROOT"/crash.log "$PROJECT_ROOT"/crash.*.log \
             "$PROJECT_ROOT"/providers/crash.log "$PROJECT_ROOT"/providers/crash.*.log; do
        if [[ -f "$f" ]]; then
            ARTIFACTS+=("$f")
            print_found "$(basename "$f") (crash log)"
        fi
    done

    # Plan files in project root (shouldn't be there)
    for f in "$PROJECT_ROOT"/*.tfplan "$PROJECT_ROOT"/tfplan; do
        if [[ -f "$f" ]]; then
            ARTIFACTS+=("$f")
            print_found "$(basename "$f") (plan file in wrong location)"
        fi
    done

    # Prepare mode: also clean terraform working files
    if [[ "$prepare_mode" == "1" ]]; then
        # .terraform directory
        if [[ -d "$PROJECT_ROOT/providers/.terraform" ]]; then
            DIRS_TO_REMOVE+=("$PROJECT_ROOT/providers/.terraform")
            print_found ".terraform/ (provider cache - regenerated by terraform init)"
        fi

        # .terraform.lock.hcl
        if [[ -f "$PROJECT_ROOT/providers/.terraform.lock.hcl" ]]; then
            ARTIFACTS+=("$PROJECT_ROOT/providers/.terraform.lock.hcl")
            print_found ".terraform.lock.hcl (lock file - regenerated by terraform init)"
        fi

        # terraform.tfstate (only if empty or has no resources)
        if [[ -f "$PROJECT_ROOT/providers/terraform.tfstate" ]]; then
            # Check if state has actual resources
            if grep -q '"resources": \[\]' "$PROJECT_ROOT/providers/terraform.tfstate" 2>/dev/null || \
               [[ ! -s "$PROJECT_ROOT/providers/terraform.tfstate" ]]; then
                ARTIFACTS+=("$PROJECT_ROOT/providers/terraform.tfstate")
                print_found "terraform.tfstate (empty state file)"
            else
                print_info "terraform.tfstate has resources - skipping (destroy infrastructure first)"
            fi
        fi

        # terraform.tfvars (user config with potential secrets/IPs)
        if [[ -f "$PROJECT_ROOT/providers/terraform.tfvars" ]]; then
            ARTIFACTS+=("$PROJECT_ROOT/providers/terraform.tfvars")
            print_found "terraform.tfvars (user config - contains your IP address)"
        fi

        # scripts/current_state/
        if [[ -d "$PROJECT_ROOT/scripts/current_state" ]] && [[ -n "$(ls -A "$PROJECT_ROOT/scripts/current_state" 2>/dev/null)" ]]; then
            DIRS_TO_REMOVE+=("$PROJECT_ROOT/scripts/current_state")
            print_found "scripts/current_state/ (runtime state)"
        fi

        # config/user.conf
        if [[ -f "$PROJECT_ROOT/config/user.conf" ]]; then
            ARTIFACTS+=("$PROJECT_ROOT/config/user.conf")
            print_found "config/user.conf (user config)"
        fi

        # Generated config files
        for f in "$PROJECT_ROOT"/config/infrastructure.*; do
            if [[ -f "$f" ]]; then
                ARTIFACTS+=("$f")
                print_found "$(basename "$f") (generated config)"
            fi
        done

        if [[ -f "$PROJECT_ROOT/config/ssh_config" ]]; then
            ARTIFACTS+=("$PROJECT_ROOT/config/ssh_config")
            print_found "ssh_config (generated config)"
        fi

        # logs/
        if [[ -d "$PROJECT_ROOT/logs" ]] && [[ -n "$(ls -A "$PROJECT_ROOT/logs" 2>/dev/null)" ]]; then
            DIRS_TO_REMOVE+=("$PROJECT_ROOT/logs")
            print_found "logs/ (log files)"
        fi

        # backup/ contents (but not .gitkeep)
        for f in "$PROJECT_ROOT"/backup/*; do
            if [[ -f "$f" ]] && [[ "$(basename "$f")" != ".gitkeep" ]]; then
                ARTIFACTS+=("$f")
                print_found "backup/$(basename "$f")"
            fi
        done
    fi

    # Return 0 if artifacts found, 1 if clean
    [[ ${#ARTIFACTS[@]} -gt 0 ]] || [[ ${#DIRS_TO_REMOVE[@]} -gt 0 ]]
}

# ==============================================================================
# Cleanup
# ==============================================================================

cleanup_artifacts() {
    local removed=0

    # Remove files
    for artifact in "${ARTIFACTS[@]}"; do
        if [[ -f "$artifact" ]]; then
            rm "$artifact"
            print_removed "$(basename "$artifact")"
            ((removed++))
        fi
    done

    # Remove directories
    for dir in "${DIRS_TO_REMOVE[@]}"; do
        if [[ -d "$dir" ]]; then
            rm -rf "$dir"
            print_removed "$(basename "$dir")/"
            ((removed++))
        fi
    done

    echo ""
    if [[ $removed -gt 0 ]]; then
        echo -e "${GREEN}Cleaned up $removed item(s)${NC}"
    fi
}

# ==============================================================================
# Usage
# ==============================================================================

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --force, -f     No confirmation prompts"
    echo "  --prepare, -p   Full cleanup for git repository preparation"
    echo "                  Removes .terraform/, state files, user configs"
    echo "  --help, -h      Show this help"
    echo ""
    echo "Examples:"
    echo "  $0              # Clean temporary artifacts (plan files, crash logs)"
    echo "  $0 --force      # Same, without prompts"
    echo "  $0 --prepare    # Full cleanup before git commit"
    echo "  $0 -p -f        # Full cleanup without prompts"
    echo ""
}

# ==============================================================================
# Main
# ==============================================================================

main() {
    local force=0
    local prepare=0

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --force|-f)
                force=1
                shift
                ;;
            --prepare|-p)
                prepare=1
                shift
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    print_header

    if [[ $prepare -eq 1 ]]; then
        echo -e "${YELLOW}Prepare mode:${NC} Full cleanup for git repository"
        echo ""
    fi

    echo "Scanning for artifacts..."
    echo ""

    if ! detect_artifacts "$prepare"; then
        print_clean "No artifacts found"
        echo ""
        exit 0
    fi

    echo ""

    if [[ $prepare -eq 1 ]] && [[ $force -eq 0 ]]; then
        echo -e "${YELLOW}Warning:${NC} This will remove terraform working files."
        echo "         You'll need to run 'terraform init' again after cloning."
        echo ""
    fi

    if [[ $force -eq 1 ]]; then
        cleanup_artifacts
    else
        echo -n "Remove these files? [y/N] "
        read -r response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            cleanup_artifacts
        else
            echo "Cleanup cancelled."
        fi
    fi

    echo ""
}

main "$@"
